### ISSUE TITLE
Self-hosting instructions with self-hosted Supabase

### ISSUE THREAD

**Issue by almereyda** [churichard/notabase#1178]
**Is your feature request related to a problem? Please describe.**

When trying to run the whole stack of Notabase oneself, some problems emerge.

1. Primarily, it is not perfectly clear on how to connect to the Supabase instance.
2. Secondly, some other email integration, preferably via SMTP or [a self-hostable email API](https://alternativeto.net/software/sendgrid/?license=opensource), can be preffered. Currently Emailoctopus is the only option.
3. Thirdly, a configuration option or command line flag for `npm start` to choose the port to listen to will help avoiding initial clashes with Supabase.
4. Last but not least, it appears image uploading does not work, as it is rejected from Supabase's storage container.

**Describe the solution you'd like**

I need a step-by-step instrauction on how to run Notabase with a custom Supabase deployment.

**Describe alternatives you've considered**

It could be nice to also have a Docker Compose environment for quickly spinning up an independent instance.

**Additional context**

What worked for me so far is the following:

1. Set up Supabase and run it from their Docker Compose in their `/docker` subdirectoy.
2. Load the Schema and storage configuration plus an initial user from within that directory:
    ```shell
    docker-compose exec -T db sh -c 'psql postgres://postgres:${POSTGRES_PASSWORD}@localhost' < ../../notabase/scripts/schema.sql
    docker-compose exec -T db sh -c 'psql postgres://postgres:${POSTGRES_PASSWORD}@localhost' < ../../notabase/scripts/storage-setup.sql
    docker-compose exec -T db sh -c 'psql postgres://postgres:${POSTGRES_PASSWORD}@localhost' < ../../notabase/scripts/seed.sql
    ```
3. Fill in the Supabase secrets from their `.env` (`ANON_KEY`, `SERVICE_ROLE_KEY`) plus the URL to the Kong Gateway (`API_EXTERNAL_URL`) into `.env.local`
4. Install the dependencies, build the project and start Notabase with Yarn.
5. Find that the Supabase Studio UI is already listening on Port 3000, stop and remove the `studio` container, adapt the Supabase`.env` again with setting the `STUDIO_PORT` to `3001` and `SITE_URL` to `http://localhost:3001`, and recreate the `studio` container.
6. Run `npm start` and find Notabase on http://localhost:3000
7. Login with the credentials provided in https://github.com/churichard/notabase/blob/main/scripts/seed.sql and use the application
8. (Optional) From within the Supabase `docker` directory, turn the example user into a super admin with:
    ```shell
    docker-compose exec -T db sh -c 'psql postgres://postgres:${POSTGRES_PASSWORD}@localhost' <<EOF
    UPDATE auth.users SET is_super_admin = true WHERE email = 'hello@example.com';
    EOF
    ```

When trying to upload an image into a document at your Notabase instance at `http://localhost:3000`, there is this error in the logs of the Supabase Compose:

```shell
supabase-kong | 192.168.32.1 - - [10/Oct/2022:12:00:52 +0000] "OPTIONS /storage/v1/object/user-assets/f5e67b94-5bd1-45aa-a399-982fa3b78bdb/126aec09-6565-40d6-8820-c5795a0e4fc9.png HTTP/1.1" 200 0 "http://localhost:3000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
supabase-kong | 2022/10/10 12:00:52 [warn] 33#0: *22089 a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000002, client: 192.168.32.1, server: kong, request: "POST /storage/v1/object/user-assets/f5e67b94-5bd1-45aa-a399-982fa3b78bdb/126aec09-6565-40d6-8820-c5795a0e4fc9.png HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:3000/"
supabase-storage | [1665403252554] INFO (7 on 8455c978c0d0): incoming request
supabase-storage |     req: {
supabase-storage |       "method": "POST",
supabase-storage |       "url": "/object/user-assets/f5e67b94-5bd1-45aa-a399-982fa3b78bdb/126aec09-6565-40d6-8820-c5795a0e4fc9.png",
supabase-storage |       "hostname": "storage:5000",
supabase-storage |       "remoteAddress": "192.168.32.3",
supabase-storage |       "remotePort": 51690
supabase-storage |     }
supabase-storage |     reqId: "req-2"
supabase-storage | [1665403252555] INFO (7 on 8455c978c0d0): content-type is multipart/form-data; boundary=---------------------------11707287482597801291672976720
supabase-storage |     reqId: "req-2"
supabase-storage |     tenantId: "stub"
supabase-storage | [1665403252564] ERROR (7 on 8455c978c0d0): error object
supabase-storage |     reqId: "req-2"
supabase-storage |     tenantId: "stub"
supabase-storage |     error: {
supabase-storage |       "hint": null,
supabase-storage |       "details": null,
supabase-storage |       "code": "23502",
supabase-storage |       "message": "null value in column \"id\" of relation \"objects\" violates not-null constraint"
supabase-storage |     }
supabase-storage | [1665403252565] INFO (7 on 8455c978c0d0): request completed
supabase-storage |     res: {
supabase-storage |       "statusCode": 400
supabase-storage |     }
supabase-storage |     responseTime: 10.429310999810696
supabase-storage |     reqId: "req-2"
supabase-storage |     tenantId: "stub"
supabase-kong | 192.168.32.1 - - [10/Oct/2022:12:00:52 +0000] "POST /storage/v1/object/user-assets/f5e67b94-5bd1-45aa-a399-982fa3b78bdb/126aec09-6565-40d6-8820-c5795a0e4fc9.png HTTP/1.1" 400 126 "http://localhost:3000/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
```

You can always use the Supabase Studio UI to review the contents in the database.

Supporting SMTP would also allow to use mailtraps like https://github.com/maildev/maildev in local development environments.

At last, I was able to use the Supabase Studio UI to create a `pro` **subscription** for the generated UUID of the `hello@example.com` **user** (with setting `stripe_customer_id` to `none`), and also added the generated UUID of the **subscription** to the **user** object, but the billing tab in the settings still shows that I am on the Basic Plan.

**Comment by almereyda** [comment]
This issue could be converted into a discussion, when not considered a valid bug report.

**Comment by almereyda** [comment]
The non-working object storage with a self-hosted Supabase instance is very likely related to:

- https://github.com/supabase/supabase/issues/4440

**Comment by kruschid** [comment]
same problem here.

caused by line 4 in https://github.com/churichard/notabase/blob/4287434a6b3a47d885e77241092ef6c2c13cc4e5/scripts/schema.sql

```
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
```

this line breaks the table `storage.object` which apparently uses the function `uuid_generate_v4()` to generate default ids.

So I simply removed that line. However `create_onboarding_notes()` stopped working after that with the error: ` function uuid_generate_v4() does not exist`.  I couldn't figure out why this is happening so I simply replaced the `uuid_generate_v4()` calls in that function with `gen_random_uuid()` which generates similar uuids but not depend on the "uuid-ossp" extension.

**Comment by kruschid** [comment]
@almereyda 

> It could be nice to also have a Docker Compose environment for quickly spinning up an independent instance.

take a look at https://github.com/kruschid/self-hosted-notabase

**Comment by almereyda** [comment]
Very much appreciated. I'd like to give this another try until the end of the year.

I'll see into providing an SMTP self host adapter, as well as a maintainable Compose environment.

**Comment by churichard** [comment]
One extra note: you probably don't need to configure the email integration if you're using it for personal use. EmailOctopus is primarily used to send a welcome message when users sign up on the hosted Notabase instance.
