### ISSUE TITLE
YunoHost inclusion?

### ISSUE THREAD

**Issue by mxmilkiib** [churichard/notabase#1604]
**Is your feature request related to a problem? Please describe.**
Could Notabase be included in the YunoHost turnkey private cloud distro?

https://yunohost.org
https://github.com/YunoHost
https://github.com/YunoHost/apps
https://yunohost.org/en/packaging_apps_intro

**Describe the solution you'd like**
YunoHost uses LDAP for cross-SaaS SSO.

**Comment by churichard** [comment]
Hey, thanks for opening this issue. I don't think we can prioritize adding Notabase to YunoHost at this time, but if more people request it then it is something we could consider doing.
