### ISSUE TITLE
Ability to do basic editing in the notes like Bold character, Italic, underscore and other markdown stuff (with hotkey if possible).

### ISSUE THREAD

**Issue by RealmX1** [churichard/notabase#1673]
The note is way less flexible and way less informative without these basic functionalities.

**Comment by churichard** [comment]
Hello! Notabase supports formatting text through a variety of methods:

1. Highlighting text and selecting a formatting option in the floating menu that pops up
2. Through using markdown shortcuts: https://help.notabase.io/markdown-shortcuts
3. Through using keyboard shortcuts: https://help.notabase.io/keyboard-shortcuts
