### ISSUE TITLE
Cursor moves to the start of the line when editing a note title

### ISSUE THREAD

**Issue by abnazhor** [churichard/notabase#2]
**Describe the bug**
When trying to edit a note title, it moves the cursor to the start of the string, making it write in the wrong direction.

**To Reproduce**
1. Go to any note
2. Click on the title to edit it
3. Write anything

**Expected behavior**
Title should be written in the right direction

**Screenshots**
![imagen](https://user-images.githubusercontent.com/11428398/119227014-406fc300-bb0c-11eb-9309-87aa23ae6eef.png)

**Desktop (please complete the following information):**
 - OS: Solus OS
 - Browser: Firefox
 - Version: 88.0.1 (64-bit)

**Comment by churichard** [comment]
Thanks for reporting this bug! It should be fixed now by https://github.com/churichard/notabase/commit/7d8b43446c254ad07e76c77a2fd20c853639c7a0.
